version: "3.7"

services:

  flask:
    build: .
    container_name: radovan_iface
    restart: always
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    volumes:
      - ./app:/app
    ports:
      - "9090:9090"
    network_mode: "host"
