version: "3.7"

services:

  flask:
    build: .
    container_name: radovan_api
    restart: always
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: UTF-8
    volumes:
      - ./app:/app
    ports:
      - "9003:9003"
    network_mode: "host"
